name: gaffe23
url: http://gaffe.cc
description: various thoughts from gaffe

permalink: /:year/:month/:day/:title/
paginate: 10
highlighter: pygments

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
